package com.example.springdemo.beans;

import org.springframework.stereotype.Component;

import com.example.springdemo.Coach;

// removed bean id to use the default one generated by the spring container
@Component
public class TennisCoach implements Coach {

	@Override
	public String getDailyWorkout() {
		return "1 Hour of Tennis practice";
	}

}
